/* Correctly-rounded bfloat16 logarithm from bf16-only tables.

   Same table layout and special-case handling as CORE-MATH's cr_log_bf16
   (T1 + T2 for normals, a direct T3 lookup for subnormals), with one change:
   every table entry is stored as bf16 rather than float32. A single bf16 per
   entry is not accurate enough -- it misrounds 8091 of the 32512 normal
   inputs -- so T1 and T2 entries are each stored as a sum of two bf16 limbs.

   The limbs are summed in float32 and rounded once. The float32 accumulation
   is NOT exact -- the limbs of one entry span far more than 24 significand
   bits, so most inputs round at least one partial sum -- but that error stays
   several orders of magnitude below bf16's rounding granularity, and the
   result is correctly rounded on every input. No FMA or compensated summation
   is needed.

   Fourteen table entries carry a last limb a few ULP off the canonical
   round-and-subtract split; without them the two-limb split misrounds 14 of
   the 32512 normal inputs. Those entries are found by search, not by
   construction, so correctness here rests on the exhaustive MPFR check in
   cross-eval/log/verify-limb.c rather than on a property of the split.
   docs/LIMB-TUNING.md describes the search.

   Storage. 32 bits per T1 and T2 entry, matching CORE-MATH's float32 tables,
   and 16 per T3 entry against 32 -- so the whole table is 1792 B against
   2048 B, a 12.5% saving. The scheme's real purpose is still targets with
   bf16 storage or bf16 MACs and no float32 table path; the saving is a bonus.

   Tables are generated by table-gen/log/limb-gen.c.
*/

#include <stdint.h>
#ifdef CORE_MATH_SUPPORT_ERRNO
#include <errno.h>
#endif

#include "logbf16-limb.h"

typedef union { __bf16 f; uint16_t u; } b16u16_limb_u;

__bf16 cr_log_bf16_limb (__bf16 x) {
  b16u16_limb_u v = {.f = x};
  uint16_t u = v.u;
  uint16_t i1 = u >> 7;
  uint16_t i2 = u & 0x7f;
  static const b16u16_limb_u nan = {.u = 0x7fc0};        // qNaN
  static const b16u16_limb_u inf = {.u = 0x7f80};        // +Inf
  static const b16u16_limb_u minus_inf = {.u = 0xff80};  // -Inf

  if (u >> 15) { // case -0 or x < 0
#ifdef CORE_MATH_SUPPORT_ERRNO
    errno = (x != 0) ? EDOM : ERANGE;
#endif
    // x + nan.f raises invalid if x = -sNaN
    return (u == 0x8000) ? minus_inf.f : x + nan.f;
  }
  if ((u >> 7) == 0xff) return inf.f + x; // NaN or Inf
  if (i1 == 0) { // subnormal case
#ifdef CORE_MATH_SUPPORT_ERRNO
    if (i2 == 0)
      errno = ERANGE; // case x = +0
#endif
    if (i2 == 0) return minus_inf.f;
    return T3L[i2][0];
  }

  /* Smallest limbs first. This is the conventional order for compensated
     accumulation; here it is not a correctness requirement, as the big-first
     order was measured to round identically on all 32512 normal inputs. The
     partial sums are not in general float32-exact -- see the note above. */
  float s = 0.0f;
  for (int k = LOGBF16_T1_LIMBS - 1; k >= 0; k--) s += (float) T1L[i1][k];
  for (int k = LOGBF16_T2_LIMBS - 1; k >= 0; k--) s += (float) T2L[i2][k];
  return (__bf16) s;
}
