/* Correctly-rounded bfloat16 logarithm from bf16-only tables.

   Same table layout and special-case handling as CORE-MATH's cr_log_bf16
   (T1 + T2 for normals, a direct T3 lookup for subnormals), with one change:
   every table entry is stored as bf16 rather than float32. A single bf16 per
   entry is not accurate enough -- it misrounds 8091 of the 32512 normal
   inputs -- so T1 and T2 entries are each stored as a sum of non-overlapping
   bf16 limbs, 3 for T1 and 2 for T2.

   The limbs are summed in float32 and rounded once. Because the split is
   error-free (each limb is the bf16 nearest what the previous ones left over),
   plain float32 addition suffices; no FMA or compensated summation is needed.

   Storage. 48 bits per T1 entry and 32 per T2, against 32 each for CORE-MATH's
   float32 tables -- this is a regression in size. The scheme is for targets
   with bf16 storage or bf16 MACs and no float32 table path, not a space
   optimization. T3 needs only one limb, so it is half the size of CORE-MATH's.

   Tables are generated by log-research/limb-gen.c.
*/

#include <stdint.h>
#ifdef CORE_MATH_SUPPORT_ERRNO
#include <errno.h>
#endif

#include "logbf16-limb.h"

typedef union { __bf16 f; uint16_t u; } b16u16_limb_u;

__bf16 cr_log_bf16_limb (__bf16 x) {
  b16u16_limb_u v = {.f = x};
  uint16_t u = v.u;
  uint16_t i1 = u >> 7;
  uint16_t i2 = u & 0x7f;
  static const b16u16_limb_u nan = {.u = 0x7fc0};        // qNaN
  static const b16u16_limb_u inf = {.u = 0x7f80};        // +Inf
  static const b16u16_limb_u minus_inf = {.u = 0xff80};  // -Inf

  if (u >> 15) { // case -0 or x < 0
#ifdef CORE_MATH_SUPPORT_ERRNO
    errno = (x != 0) ? EDOM : ERANGE;
#endif
    // x + nan.f raises invalid if x = -sNaN
    return (u == 0x8000) ? minus_inf.f : x + nan.f;
  }
  if ((u >> 7) == 0xff) return inf.f + x; // NaN or Inf
  if (i1 == 0) { // subnormal case
#ifdef CORE_MATH_SUPPORT_ERRNO
    if (i2 == 0)
      errno = ERANGE; // case x = +0
#endif
    if (i2 == 0) return minus_inf.f;
    return T3L[i2][0];
  }

  /* Smallest limbs first. The split is error-free and every partial sum is
     float32-representable, so the big-first order rounds identically on all
     32512 normal inputs -- this order is the conventional one for compensated
     accumulation, not a correctness requirement here. */
  float s = 0.0f;
  for (int k = LOGBF16_T1_LIMBS - 1; k >= 0; k--) s += (float) T1L[i1][k];
  for (int k = LOGBF16_T2_LIMBS - 1; k >= 0; k--) s += (float) T2L[i2][k];
  return (__bf16) s;
}
