/* Compute per-input lower/upper bounds on ln(x) for the T1/T2 linear program.

   Step 2 of the workflow (precompute.cc is step 1; this file also emits step 3's
   constraint file, lp-constraints.txt). For every valid bf16 input x we already
   know the correctly-rounded result y = round_bf16(ln x). The reconstruction the
   table must satisfy is a real sum S = T1[i1] + T2[i2]; correct rounding (RNDN)
   holds exactly when S lands in the open rounding interval around y:

       lb = (y_prev + y) / 2        ub = (y + y_next) / 2
       lb < S < ub   =>   round_bf16(S) = y

   y_prev / y_next are the adjacent bf16 values bracketing y. Because y itself is
   derived from the precomputed ln(x), lb and ub are fully determined by the
   precompute (task requirement: "lb = ln(x_L), the next lowest value from ln(x);
   ub = ln(x_H), the next highest"). We print lb, y, ub in both exact hex and
   decimal so the bounds are auditable, and the midpoints are computed in high
   precision so no bound is itself rounded.

   Scope of the LP: only NORMAL inputs (exp field 1..254) use S = T1[i1] + T2[i2].
   Subnormal inputs (exp == 0) are served by CORE-MATH's separate T3 table and are
   reported here but marked NON-LP, so the emitted constraints cover exactly the
   T1/T2 unknowns.

   Two outputs:
     - stdout  -> log-research/ln-bounds.txt       (human-readable bounds table)
     - file    -> log-research/lp-constraints.txt   (paste into an LP / MILP solver)

   Build (no C++ backend on this host; compile as C, matching inria-log16bitp.c):
     gcc -O2 -xc -std=c11 log-research/bound-calc.cc \
         -I/usr/include/x86_64-linux-gnu -lmpfr -lgmp -lm -o log-research/bound-calc
     ./log-research/bound-calc */

#include <stdint.h>
#include <stdio.h>
#include <mpfr.h>

typedef union { __bf16 f; uint16_t u; } b16u16;

#define BF16_PREC 8
#define BF16_EMIN (-133)
#define BF16_EMAX 128
#define WORK_PREC 200

#define LP_FILE "log-research/lp-constraints.txt"

/* bf16 neighbors: n_prev = largest bf16 < y, n_next = smallest bf16 > y, using
   MPFR's directed nextbelow/nextabove within the bf16 exponent range. y must be
   finite. Results are exact bf16 values held at BF16_PREC. */
static void bf16_neighbors (mpfr_t y, mpfr_t n_prev, mpfr_t n_next) {
  mpfr_exp_t emin = mpfr_get_emin (), emax = mpfr_get_emax ();
  mpfr_set_emin (BF16_EMIN);
  mpfr_set_emax (BF16_EMAX);

  mpfr_set_prec (n_prev, BF16_PREC);
  mpfr_set (n_prev, y, MPFR_RNDN);
  mpfr_nextbelow (n_prev);

  mpfr_set_prec (n_next, BF16_PREC);
  mpfr_set (n_next, y, MPFR_RNDN);
  mpfr_nextabove (n_next);

  mpfr_set_emin (emin);
  mpfr_set_emax (emax);
}

/* y = round_bf16(value), RNDN, bf16 exponent range; also 16-bit pattern in *bits. */
static void bf16_round (mpfr_t value, mpfr_t y, uint16_t *bits) {
  mpfr_exp_t emin = mpfr_get_emin (), emax = mpfr_get_emax ();
  mpfr_set_emin (BF16_EMIN);
  mpfr_set_emax (BF16_EMAX);
  mpfr_set_prec (y, BF16_PREC);
  int inex = mpfr_set (y, value, MPFR_RNDN);
  mpfr_subnormalize (y, inex, MPFR_RNDN);
  mpfr_set_emin (emin);
  mpfr_set_emax (emax);
  b16u16 v;
  v.f = (__bf16) mpfr_get_d (y, MPFR_RNDN);
  *bits = v.u;
}

int main (void) {
  mpfr_set_emin (BF16_EMIN);
  mpfr_set_emax (BF16_EMAX);

  FILE *lp = fopen (LP_FILE, "w");
  if (!lp) { perror ("fopen " LP_FILE); return 1; }

  mpfr_t x, lnx, y, n_prev, n_next, lb, ub;
  mpfr_init2 (x, WORK_PREC);
  mpfr_init2 (lnx, WORK_PREC);
  mpfr_init2 (y, BF16_PREC);
  mpfr_init2 (n_prev, BF16_PREC);
  mpfr_init2 (n_next, BF16_PREC);
  mpfr_init2 (lb, WORK_PREC);
  mpfr_init2 (ub, WORK_PREC);

  printf ("# ln(x) rounding bounds for all valid bfloat16 inputs (MPFR %s)\n",
          mpfr_get_version ());
  printf ("# lb=(y_prev+y)/2, ub=(y+y_next)/2; edge open/closed by ties-to-even\n");
  printf ("#   y even -> [lb,ub] rounds to y (closed); y odd -> (lb,ub) (open)\n");
  printf ("# columns: u,i1,i2,scope,edge,lb_hex,ub_hex,y_hex,y_bits,lb_dec,ub_dec\n");

  /* LP file preamble: variables and objective. Each T1[k]/T2[k] is an unknown
     real; the correctly-rounded 16-bit table value is recovered by rounding the
     solved reals to bf16 afterward. */
  fprintf (lp, "\\ Linear program for correctly-rounded bf16 ln() tables T1, T2\n");
  fprintf (lp, "\\ Generated by log-research/bound-calc.cc (MPFR %s)\n",
           mpfr_get_version ());
  fprintf (lp, "\\ Unknowns: T1[0..255], T2[0..127] (real). Each normal input u\n");
  fprintf (lp, "\\ contributes  lb_u < T1[i1] + T2[i2] < ub_u  with i1=u>>7, i2=u&0x7f.\n");
  fprintf (lp, "\\ LP format uses <= . Rounding interval endpoints follow ties-to-even:\n");
  fprintf (lp, "\\ y even -> closed [lb,ub] (midpoint verbatim); y odd -> open, each side\n");
  fprintf (lp, "\\ tightened by EPS=1e-9 to model strict < within LP's <= form.\n");
  fprintf (lp, "\\ Anchor: T1[127]=0 (ln(2^0)=0) removes the T1/T2 additive gauge freedom.\n");
  /* Pure feasibility: zero objective. GLPK's LP parser rejects a bare "obj: 0"
     (needs a variable term), so reference one var with coefficient 0. */
  fprintf (lp, "Minimize\n obj: 0 T1_1\n");
  fprintf (lp, "Subject To\n");

  const double EPS = 1e-9;
  long count = 0, lp_rows = 0;

  for (uint32_t uu = 0; uu <= 0xFFFF; uu++) {
    uint16_t u = (uint16_t) uu;
    b16u16 v; v.u = u;
    uint16_t exp = (u >> 7) & 0xFF;
    uint16_t mant = u & 0x7f;
    if (u >> 15) continue;      /* -0 or negative */
    if (exp == 0xFF) continue;  /* +Inf / NaN */
    if (u == 0x0000) continue;  /* x=+0 -> ln=-Inf, no finite rounding interval */

    uint16_t i1 = u >> 7;
    uint16_t i2 = mant;
    int normal = (exp != 0);
    const char *scope = normal ? "LP" : "NON-LP";

    mpfr_set_d (x, (double) (float) v.f, MPFR_RNDN);
    mpfr_log (lnx, x, MPFR_RNDN);

    uint16_t ybits;
    bf16_round (lnx, y, &ybits);
    bf16_neighbors (y, n_prev, n_next);

    /* lb = (y_prev + y)/2, ub = (y + y_next)/2 in high precision (exact halves). */
    mpfr_add (lb, n_prev, y, MPFR_RNDN);
    mpfr_div_2ui (lb, lb, 1, MPFR_RNDN);
    mpfr_add (ub, y, n_next, MPFR_RNDN);
    mpfr_div_2ui (ub, ub, 1, MPFR_RNDN);

    /* Ties-to-even endpoint rule: a midpoint rounds to whichever neighbor has an
       even significand. So the midpoints lb and ub round to y exactly when y's
       significand LSB is 0 (y even). Then the admissible interval is CLOSED
       [lb, ub]; when y is odd it is OPEN (lb, ub). Encode this so the constraint
       set is exactly {S : round_bf16(S) = y} and the LP is never spuriously
       infeasible at a tie. */
    int y_even = ((ybits & 1u) == 0);
    const char *edge = y_even ? "closed" : "open";

    char lb_hex[80], ub_hex[80], y_hex[80], lb_dec[80], ub_dec[80];
    mpfr_snprintf (lb_hex, sizeof lb_hex, "%Ra", lb);
    mpfr_snprintf (ub_hex, sizeof ub_hex, "%Ra", ub);
    mpfr_snprintf (y_hex, sizeof y_hex, "%Ra", y);
    mpfr_snprintf (lb_dec, sizeof lb_dec, "%.17Rg", lb);
    mpfr_snprintf (ub_dec, sizeof ub_dec, "%.17Rg", ub);

    printf ("%u,%u,%u,%s,%s,%s,%s,%s,0x%04X,%s,%s\n",
            u, i1, i2, scope, edge, lb_hex, ub_hex, y_hex, ybits, lb_dec, ub_dec);
    count++;

    if (!normal) continue; /* subnormals go through T3, not the T1/T2 LP */

    /* Two rows per input: T1[i1] + T2[i2] bounded below by lb and above by ub.
       Closed side (y even): use the midpoint verbatim (tie rounds to y).
       Open side  (y odd) : tighten by EPS so the strict inequality is modeled
       within LP's <= form.  (Both unknowns have coefficient +1.) */
    double lbd = mpfr_get_d (lb, MPFR_RNDN);
    double ubd = mpfr_get_d (ub, MPFR_RNDN);
    double lo = y_even ? lbd : lbd + EPS;
    double hi = y_even ? ubd : ubd - EPS;
    fprintf (lp, " c%ld_lo: T1_%u + T2_%u >= %.17g\n", (long) u, i1, i2, lo);
    fprintf (lp, " c%ld_hi: T1_%u + T2_%u <= %.17g\n", (long) u, i1, i2, hi);
    lp_rows += 2;
  }

  /* Gauge fix: T1[127] corresponds to ln(2^0)=0. Pin it so the solver returns a
     unique T1/T2 split rather than any additive-shift equivalent. */
  fprintf (lp, " anchor: T1_127 = 0\n");

  /* Free variables: LP format defaults to x>=0, but log tables go negative. */
  fprintf (lp, "Bounds\n");
  for (int k = 0; k <= 255; k++) fprintf (lp, " T1_%d free\n", k);
  for (int k = 0; k <= 127; k++) fprintf (lp, " T2_%d free\n", k);
  fprintf (lp, "End\n");

  fclose (lp);
  fprintf (stderr, "bound-calc: %ld inputs bounded, %ld LP constraint rows -> %s\n",
           count, lp_rows, LP_FILE);

  mpfr_clear (x); mpfr_clear (lnx); mpfr_clear (y);
  mpfr_clear (n_prev); mpfr_clear (n_next);
  mpfr_clear (lb); mpfr_clear (ub);
  return 0;
}
