/* Generate the 3xT1 + 2xT2 bf16 limb tables for cr_log_bf16_limb.

   Why limbs. A single bf16 table entry carries 8 significand bits, which is
   not enough: T1[i1]+T2[i2] then misrounds 8091 of the 32512 normal bf16
   inputs. Storing each ideal as a sum of bf16 limbs recovers precision using
   only bf16 storage -- the target here is hardware that has bf16 storage or
   bf16 MACs and no float32 table path.

   Split. Iterated round-and-subtract: limb k is the bf16 nearest to what the
   previous limbs left over. The limbs are non-overlapping by construction, so
   an ordinary float32 accumulation of them is exact enough to round correctly;
   no compensated summation is needed.

   Widths. 3 limbs for T1, 2 for T2. T1 spans +/-88 while T2 spans [0,ln2), so
   T1's residual after two limbs is still large enough to misround 14 inputs;
   T2's is not. 3x2 is the smallest configuration reaching zero.

   T3 is not emitted: the subnormal band already solves at plain bf16 width.

   Usage: limb-gen [OUT_FILE]     (default implementations/log/logbf16-limb.h)
   Run from the repo root.
*/

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <mpfr.h>

#define WORK_PREC 300
#define BF16_PREC 8
#define T1_LIMBS 3
#define T2_LIMBS 2
#define T1_N 256
#define T2_N 128
#define T3_N 128

typedef union { __bf16 f; uint16_t u; } b16u16_u;

/* Nearest bf16 to `v`, returned as a double (exact -- bf16 is a float subset). */
static double round_bf16 (mpfr_t v) {
  b16u16_u t;
  t.f = (__bf16) mpfr_get_d (v, MPFR_RNDN);
  return (double) t.f;
}

/* Split `ideal` into `n` bf16 limbs by iterated round-and-subtract.
   Residual arithmetic is exact: each subtraction is of a bf16 from a
   WORK_PREC value, and WORK_PREC leaves ample room. */
static void split_limbs (mpfr_t ideal, double *limb, int n, mpfr_t residual) {
  mpfr_set (residual, ideal, MPFR_RNDN);
  for (int k = 0; k < n; k++) {
    limb[k] = round_bf16 (residual);
    mpfr_sub_d (residual, residual, limb[k], MPFR_RNDN);
  }
}

static void emit_table (FILE *out, const char *name, const char *comment,
                        double (*limb)[4], int rows, int nlimb) {
  fprintf (out, "%s\n", comment);
  fprintf (out, "static const __bf16 %s[%d][%d] = {\n", name, rows, nlimb);
  for (int i = 0; i < rows; i++) {
    fprintf (out, "  {");
    for (int k = 0; k < nlimb; k++)
      fprintf (out, "%s%af", k ? ", " : "", limb[i][k]);
    fprintf (out, "},%s", (i % 2) ? "\n" : "");
  }
  if (rows % 2) fprintf (out, "\n");
  fprintf (out, "};\n\n");
}

int main (int argc, char **argv) {
  const char *out_file = (argc > 1) ? argv[1]
                                    : "implementations/log/logbf16-limb.h";

  mpfr_t ln2, ideal, residual;
  mpfr_init2 (ln2, WORK_PREC);
  mpfr_init2 (ideal, WORK_PREC);
  mpfr_init2 (residual, WORK_PREC);
  mpfr_const_log2 (ln2, MPFR_RNDN);

  static double t1[T1_N][4], t2[T2_N][4], t3[T3_N][4];

  /* T1[k] approximates ln(2^(k-127)) = (k-127)*ln2. k=0 and k=255 are the
     subnormal and NaN/Inf slots; cr_log_bf16 never sums them, so leave them
     zero to match the shipping table's shape. */
  for (int k = 1; k < T1_N - 1; k++) {
    mpfr_mul_si (ideal, ln2, k - 127, MPFR_RNDN);
    split_limbs (ideal, t1[k], T1_LIMBS, residual);
  }

  /* T2[k] approximates ln(1 + k/128). */
  for (int k = 0; k < T2_N; k++) {
    mpfr_set_si (ideal, 128 + k, MPFR_RNDN);
    mpfr_div_si (ideal, ideal, 128, MPFR_RNDN);
    mpfr_log (ideal, ideal, MPFR_RNDN);
    split_limbs (ideal, t2[k], T2_LIMBS, residual);
  }

  /* T3[k] serves the subnormal input x = k * 2^-133 directly -- a lookup, not
     a summand. One bf16 limb suffices; the MILP fragment frag-t3-only proves
     the whole 127-entry band feasible on the plain bf16 grid. T3[0] is
     ln(+0) = -Inf, hardcoded by the caller and left zero here. */
  for (int k = 1; k < T3_N; k++) {
    mpfr_set_si (ideal, k, MPFR_RNDN);
    mpfr_mul_2si (ideal, ideal, -133, MPFR_RNDN);
    mpfr_log (ideal, ideal, MPFR_RNDN);
    split_limbs (ideal, t3[k], 1, residual);
  }

  FILE *out = fopen (out_file, "w");
  if (!out) {
    fprintf (stderr, "limb-gen: cannot write %s\n", out_file);
    return 1;
  }

  fprintf (out,
    "/* Generated by log-research/limb-gen.c -- do not edit by hand.\n"
    "\n"
    "   bf16 limb tables for cr_log_bf16_limb: each ln() table entry is stored\n"
    "   as a sum of non-overlapping bf16 limbs (%d for T1, %d for T2), so the\n"
    "   table needs no float32 storage. Accumulating the limbs in float32 and\n"
    "   rounding once reproduces correctly-rounded bf16 ln() on every input.\n"
    "*/\n\n"
    "#pragma once\n\n"
    "/* Every literal below is an exact bf16 value, so the initialiser loses\n"
    "   nothing. C++ still warns on the double->__bf16 conversion rank, which\n"
    "   is noise here -- silence it for the tables only. */\n"
    "#ifdef __cplusplus\n"
    "#pragma GCC diagnostic push\n"
    "#pragma GCC diagnostic ignored \"-Wconversion\"\n"
    "#endif\n\n"
    "#define LOGBF16_T1_LIMBS %d\n"
    "#define LOGBF16_T2_LIMBS %d\n\n",
    T1_LIMBS, T2_LIMBS, T1_LIMBS, T2_LIMBS);

  emit_table (out, "T1L",
    "/* T1L[i1] sums to ln(x1), x1 the bf16 with encoding i1*2^7. */",
    t1, T1_N, T1_LIMBS);
  emit_table (out, "T2L",
    "/* T2L[i2] sums to ln(x2), 1 <= x2 < 2, i2 the low 7 encoding bits. */",
    t2, T2_N, T2_LIMBS);
  emit_table (out, "T3L",
    "/* T3L[i2] is ln(i2 * 2^-133) outright -- the subnormal band is a direct\n"
    "   lookup, so one bf16 limb is enough. T3L[0] is unused (ln(+0) = -Inf). */",
    t3, T3_N, 1);

  fprintf (out,
    "#ifdef __cplusplus\n"
    "#pragma GCC diagnostic pop\n"
    "#endif\n");
  fclose (out);

  mpfr_clear (ln2); mpfr_clear (ideal); mpfr_clear (residual);
  printf ("limb-gen: %d T1 x %d limbs, %d T2 x %d limbs, %d T3 x 1 limb -> %s\n",
          T1_N, T1_LIMBS, T2_N, T2_LIMBS, T3_N, out_file);
  return 0;
}
