/* Correctly-rounded bfloat16 sine from bf16-only tables.

   Same three regimes and special-case handling as CORE-MATH's cr_sin_bf16,
   with one change: every table entry is stored as bf16 rather than float32,
   as a sum of non-overlapping limbs.

   As in the exp version, no product is expanded. Splitting both sides of a
   product multiplies out into cross terms; instead each FACTOR is rebuilt from
   its limbs in float32 and the shipped expression runs unchanged -- the mid
   path's fma(S1, C2, C1 * S2), and the large path's angle-addition chain.

   Two variants ship:

     cr_sin_bf16_limb      3 limbs on all six tables. Exact -- three bf16 limbs
                           carry 24 significand bits, exactly float32's, so
                           the output is identical to cr_sin_bf16 by
                           construction rather than by testing.

     cr_sin_bf16_limb_min  3 limbs on S1/C1 and S3/C3, 2 on S2/C2. The mid path
                           is the same 3x2 shape that solves ln and exp: three
                           of the 128 (S2,C2) index pairs carry a one-ULP
                           adjustment. Correctly rounded on all 65536 inputs,
                           verified exhaustively against MPFR.

   S3/C3 keep three limbs in both variants. The large path chains up to eight
   lookups and reuses each entry across many inputs, so its errors compound and
   the per-entry independence that makes the mid path tunable does not hold --
   two limbs there misround 70 inputs and no per-entry choice repairs them.

   Storage, against 4056 B of float32 tables: 6084 B exact (+50%), 5572 B
   minimal (+37%). Like the ln and exp versions this is a size regression --
   the scheme targets hardware with bf16 storage or bf16 MACs and no float32
   table path, not a space saving.

   Tables are generated by log-research/sin-limb-gen.c.
*/

#include <stdint.h>
#ifdef CORE_MATH_SUPPORT_ERRNO
#include <errno.h>
#endif

#include "sinbf16-limb.h"

typedef union { __bf16 f; uint16_t u; } b16u16_slimb;

static const float sgn_limb[] = {1.0f, -1.0f};

static inline float rebuild (const __bf16 *limb, int n) {
  float s = 0.0f;
  for (int k = n - 1; k >= 0; k--) s += (float) limb[k];
  return s;
}

/* Shared prologue: the small-|x| regime and NaN/Inf, identical to
   cr_sin_bf16. Returns 1 and sets *out when x is handled here. */
static inline int sin_prologue (__bf16 x, uint16_t u, uint16_t au, __bf16 *out) {
  // for |x| <= 0x1.dp-4, sin(x) rounds to x to nearest
  if (au <= 0x3de8) { // |x| <= 0x1.dp-4
    if (au == 0) { *out = x; return 1; } // x = +0 or -0
    float res;
    // avoid spurious underflow for |x|=0x1p-126
    res = (au == 0x80) ? sgn_limb[u >> 15] * 0x1.fffffcp-127f
                       : (float) x * 0x1.fffffep-1f;
#ifdef CORE_MATH_SUPPORT_ERRNO
    if (__builtin_fabsf (res) < 0x1p-126)
      errno = ERANGE; // underflow
#endif
    *out = (__bf16) res;
    return 1;
  }
  if (au >= 0x4580 && (au >> 7) == 0xff) { // NaN or Inf
    b16u16_slimb qnan = {.u = 0x7fc0};
    *out = qnan.f + x;
    return 1;
  }
  return 0;
}

/* Large path: |x| >= 4096, ulp(x) >= 32. |x| = b0*2^i + ... + b7*2^(i+7),
   accumulated with sin(a+b) = sin a cos b + cos a sin b and its cosine
   companion. Both variants use the exact 3-limb S3/C3 tables. */
static inline float sin_large (uint16_t au) {
  int k = (au >> 7) - 0x8b; // k=0 for |x|=4096
  float s = rebuild (S3L[k + 7], SINBF16_LIMBS_EXACT);
  float c = rebuild (C3L[k + 7], SINBF16_LIMBS_EXACT);
  for (int j = 0; j < 7; j++)
    if ((au >> j) & 1) {
      float sj = rebuild (S3L[k + j], SINBF16_LIMBS_EXACT);
      float cj = rebuild (C3L[k + j], SINBF16_LIMBS_EXACT);
      float t = __builtin_fmaf (s, cj, c * sj);
      c = __builtin_fmaf (c, cj, -s * sj);
      s = t;
    }
  return s;
}

/* 3-limb everywhere: exact reconstruction, bit-identical to cr_sin_bf16. */
__bf16 cr_sin_bf16_limb (__bf16 x) {
  b16u16_slimb v = {.f = x};
  uint16_t u = v.u, au = u & 0x7fff;
  __bf16 out;
  if (sin_prologue (x, u, au, &out)) return out;

  if (au < 0x4580) { // |x| < 4096; the exponent part lies in [123,138]
    uint16_t i1 = (au - 0x3d80) >> 3; // 0x3d80 is 123<<7
    uint16_t i2 = (((au - 0x3d80) >> 7) << 3) | (au & 0x7);
    // we use a FMA to fix the evaluation order
    float res = __builtin_fmaf (rebuild (S1L[i1], SINBF16_LIMBS_EXACT),
                                rebuild (C2L[i2], SINBF16_LIMBS_EXACT),
                                rebuild (C1L[i1], SINBF16_LIMBS_EXACT)
                              * rebuild (S2L[i2], SINBF16_LIMBS_EXACT));
    return (__bf16) (sgn_limb[u >> 15] * res);
  }
  return (__bf16) (sgn_limb[u >> 15] * sin_large (au));
}

/* Minimal: S2/C2 at two limbs, three index pairs tuned by one ULP. */
__bf16 cr_sin_bf16_limb_min (__bf16 x) {
  b16u16_slimb v = {.f = x};
  uint16_t u = v.u, au = u & 0x7fff;
  __bf16 out;
  if (sin_prologue (x, u, au, &out)) return out;

  if (au < 0x4580) {
    uint16_t i1 = (au - 0x3d80) >> 3;
    uint16_t i2 = (((au - 0x3d80) >> 7) << 3) | (au & 0x7);
    float res = __builtin_fmaf (rebuild (S1L[i1], SINBF16_LIMBS_EXACT),
                                rebuild (C2M[i2], SINBF16_LIMBS_MIN),
                                rebuild (C1L[i1], SINBF16_LIMBS_EXACT)
                              * rebuild (S2M[i2], SINBF16_LIMBS_MIN));
    return (__bf16) (sgn_limb[u >> 15] * res);
  }
  return (__bf16) (sgn_limb[u >> 15] * sin_large (au));
}
