/* Correctly-rounded bfloat16 exponential from bf16-only tables.

   Same table layout and special-case handling as CORE-MATH's cr_exp_bf16
   (T1[i1] * T2[i2] for the table path), with one change: every table entry is
   stored as bf16 rather than float32, as a sum of non-overlapping limbs.

   The product is not expanded. cr_log_bf16 ends in a sum, so its limbs stay
   linear and the ln version simply adds all five. A product does not work that
   way -- splitting both factors and multiplying out gives n*m cross terms --
   which is why EXP-LIMB-PLAN.md read exp as a dead end. The way round it is to
   reconstruct each FACTOR from its limbs first, in float32, and then do the
   single multiply CORE-MATH already does. That costs n+m adds and one multiply
   at any limb count, and the table still holds nothing but bf16.

   Two variants ship:

     cr_exp_bf16_limb      3 limbs on T1, 3 on T2. Exact -- three bf16 limbs
                           carry 24 significand bits, exactly float32's, so
                           each reconstructed factor IS the shipped float32
                           and the output is identical to cr_exp_bf16 by
                           construction rather than by testing.

     cr_exp_bf16_limb_min  2 limbs on T1, 2 on T2. Neither factor is exact
                           here, so the significand-width argument above does
                           not apply and correctness is not free: the canonical
                           split misrounds three of the 3954 table-path inputs.
                           T1[16], T2[105] and T2[182] carry a small second-limb
                           adjustment (+1, +2, +1 ULP) which repairs all three.
                           Correctly rounded on all 65536 inputs, verified
                           exhaustively against MPFR -- that check IS the proof
                           here, not a confirmation of one.

   Storage, against 3072 B of float32 tables: 4608 B at 3x3 (+50%), and 3072 B
   at 2x2 -- exact parity. Unlike the ln version, the minimal exp table is not
   a size regression at all: it buys bf16-only storage for nothing. The scheme
   still targets hardware with bf16 storage or bf16 MACs and no float32 table
   path; on exp it now costs such hardware no extra space to get there.

   Why 2x2 is reachable when EXP-LIMB-PLAN.md said it was not: with both
   factors inexact the correctness rows are bilinear, which rules out the
   per-entry search that 3x2 used. But only three inputs actually break, and
   they read three disjoint entries, so the repairs do not interact and
   bounded coordinate descent finds them in one pass. See exp-limb-gen.c.

   Tables are generated by log-research/exp-limb-gen.c.
*/

#include <stdint.h>
#ifdef CORE_MATH_SUPPORT_ERRNO
#include <errno.h>
#endif

#include "expbf16-limb.h"

typedef union { __bf16 f; uint16_t u; } b16u16_elimb;

/* Smallest limb first. The split is error-free and every partial sum is
   float32-representable, so the order does not change the result; this is the
   conventional order for compensated accumulation. */
static inline float rebuild (const __bf16 *limb, int n) {
  float s = 0.0f;
  for (int k = n - 1; k >= 0; k--) s += (float) limb[k];
  return s;
}

/* Shared special-case handling, identical to cr_exp_bf16. Returns 1 and sets
   *out when x is handled off the table path; otherwise fills the two indices. */
static inline int exp_prologue (__bf16 x, __bf16 *out, uint16_t *i1, uint16_t *i2) {
  b16u16_elimb v = {.f = x};
  uint16_t u = v.u, au = u & 0x7fff;

  // for -0x1p-9 <= x <= 0x1.fep-9, exp(x) rounds to 1 to nearest
  if (au <= 0x3b00) { // |x| <= 0x1p-9
    if (au == 0) { *out = (__bf16) 1.0f; return 1; } // x = +0 or -0
    *out = (__bf16) (1.0f + ((au == u) ? 0x1p-24f : -0x1p-25f));
    return 1;
  }

#ifdef CORE_MATH_SUPPORT_ERRNO
  if (au >= 0x42b2 && au == u) // x >= 0x1.64p+6
    errno = ERANGE; // overflow
  if (au >= 0x42af && au != u) // x <= -0x1.5ep+6
    errno = ERANGE; // underflow
#endif

  // for x >= 0x1.64p+6, exp(x) > 2^128
  // for x <= -0x1.74p+6, exp(x) < 2^-134
  if (au >= 0x42ba) { // |x| >= 0x1.74p+6
    if (au >= 0x7f80) { // case Inf or NaN
      if (u == 0xff80) { *out = (__bf16) 0.0f; return 1; } // -Inf
      *out = x + x; return 1; // +Inf or NaN
    }
    *out = (__bf16) ((au == u) ? 0x1p+127f + 0x1p+127f : 0x1p-134f);
    return 1;
  }

  // now 0x3b00 < au < 0x42ba thus the range of au fits on 11 bits
  // more precisely the exponent part lies in [118,133]
  *i1 = ((u >> 15) << 8) + (au >> 3) - 0x760;
  *i2 = ((u >> 15) << 7) + (((au >> 7) << 3) | (au & 0x7)) - 0x3b0;
  return 0;
}

/* 3x3: exact reconstruction, bit-identical to cr_exp_bf16. */
__bf16 cr_exp_bf16_limb (__bf16 x) {
  __bf16 out; uint16_t i1, i2;
  if (exp_prologue (x, &out, &i1, &i2)) return out;
  return (__bf16) (rebuild (T1L[i1], EXPBF16_T1_LIMBS)
                 * rebuild (T2L[i2], EXPBF16_T2_LIMBS_EXACT));
}

/* 2x2: minimal, three entries tuned by one or two ULP. Storage parity with
   the float32 tables, and one fewer dependent add on each factor's chain. */
__bf16 cr_exp_bf16_limb_min (__bf16 x) {
  __bf16 out; uint16_t i1, i2;
  if (exp_prologue (x, &out, &i1, &i2)) return out;
  return (__bf16) (rebuild (T1M[i1], EXPBF16_T1_LIMBS_MIN)
                 * rebuild (T2M[i2], EXPBF16_T2_LIMBS_MIN));
}
